---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nodejsps-app
  namespace: default
  labels:
    app: nodejsps-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejsps-app
  template:
    metadata:
      labels:
        app: nodejsps-app
    spec:
      containers:
      - name: nodejsps-app
        image: "sudrasan/apiservice"
        ports:
          - containerPort: 3333
---
apiVersion: v1
kind: Service
metadata:
  name: nodejsps-app
  namespace: default
spec:
  selector:
    app: nodejsps-app
  type: LoadBalancer
  ports:
  - name: http
    targetPort: 3333
    port: 80