apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: sudrasan/build
          resources:
            limits:
              memory: "384Mi"
              cpu: "500m"
          ports:
            - containerPort: 4000
        - name: server1
          image: sudrasan/datainjector
          resources:
            limits:
              memory: "384Mi"
              cpu: "500m"
          ports:
            - containerPort: 4002
        - name: server2
          image: sudrasan/secondserver
          resources:
            limits:
              memory: "384Mi"
              cpu: "500m"
          ports:
            - containerPort: 4004
        - name: server3
          image: sudrasan/gprm
          resources:
            limits:
              memory: "384Mi"
              cpu: "500m"
          ports:
            - containerPort: 4006

---
apiVersion: v1
kind: Service
metadata:
  name: server-1-service
spec:
  type: LoadBalancer
  selector:
    app: server
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: server-2-service
spec:
  type: LoadBalancer
  selector:
    app: server
    # containers: server1
  ports:
    - protocol: TCP
      port: 4002
      targetPort: 4002
---
apiVersion: v1
kind: Service
metadata:
  name: server-3-service
spec:
  type: LoadBalancer
  selector:
    app: server
    # containers: server1
  ports:
    - protocol: TCP
      port: 4004
      targetPort: 4004
---
apiVersion: v1
kind: Service
metadata:
  name: server-4-service
spec:
  type: LoadBalancer
  selector:
    app: server
    # containers: server1
  ports:
    - protocol: TCP
      port: 4006
      targetPort: 4006

